### PR TITLE
Add icon from scratch topic

### PR DESCRIPTION
**Pull request by hello-smile6**
https://scratch.mit.edu/discuss/topic/568857/

### CODE REVIEW

**Comment by imdevarsh** [comment]
That's not an icon, that's a screenshot...

**Comment by hello-smile6** [comment]
> That's not an icon, that's a screenshot...

You know what I mean, 🙄 Also, I'm running prettier right now.

**Comment by hello-smile6** [comment]
Ugh, why didn't you commit a `package-lock`?

**Comment by hello-smile6** [comment]
@webdev03 Could you approve workflow run?

**Comment by imdevarsh** [comment]
Please use PNPM in your commits. Or, don't add your package lock.

**Comment by hello-smile6** [comment]
> Please use PNPM in your commits. Or, don't add your package lock.

Okay, why use pnpm?

**Comment by imdevarsh** [comment]
pnpm = better

**Comment by hello-smile6** [comment]
> pnpm = better

Fine. It's in corepack, so I'll use it. Making another PR.

**Comment by imdevarsh** [comment]
pnpm isn't junk...
I'm confused why people hate pnpm so much!

**Comment by hello-smile6** [comment]
> pnpm isn't junk... I'm confused why people hate pnpm so much!

It doesn't auto-delete unused dependencies. Also, it uses YAML for its lockfile.

**Comment by imdevarsh** [comment]
`pnpm store prune`
Nobody goes in the lockfile anyways.

**Comment by hello-smile6** [comment]
> `pnpm store prune` Nobody goes in the lockfile anyways.

Um, I do. And others do, too: When they're resolving conflict he**.

**Comment by imdevarsh** [comment]
When you're resolving conflicts, even if it is JSON, wouldn't help!

**Comment by hello-smile6** [comment]
> When you're resolving conflicts, even if it is JSON, wouldn't help!

Yes, it would. I usually just nuke the lockfile and `npm i` when I have conflicts.

**Comment by imdevarsh** [comment]
Nuking the lockfile broke my app for 5 hours. Don't do it.

**Comment by imdevarsh** [comment]
@hello-smile6 you should check out #1

**Pull request merged**
