### PR TITLE
Add `pnpm` enable script

### PR DESCRIPTION
**Pull request by hello-smile6**

### CODE REVIEW

**Comment by imdevarsh** [comment]
I don't see how this is necessary, I'll just add that in the readme later.

**Comment by hello-smile6** [comment]
> I don't see how this is necessary, I'll just add that in the readme later.

☹️

**Comment by imdevarsh** [comment]
Tell me why I should merge this.

**Comment by hello-smile6** [comment]
> Tell me why I should merge this.

Because then people don't waste bandwidth doing `npm i -g pnpm` when they already have it.

**Comment by imdevarsh** [comment]
Corepack has to be manually enabled.

**Pull request closed without merging**
